print('-=-' * 30)
litros = int(input('Digite a capacidade de litros que cabe no tanque da sua moto: '))
print('-=-' * 30)
gas = float(input('Digite o valor da gasolina: R$ '))
print('-=-' * 30)
km = int(input('Digite a quantidade de km percorrido:  '))
print('-=-' * 30)
s = (gas * km)
gasl = (gas * litros)

print('Você vai gastar o total de R${:.2f}, para encher totalmente o tanque da sua moto.'.format(gasl))
print('-=-' * 30)
print('{} Litros equivale a R${:.2f}. '.format(km, s))
print('-=-' * 30)