a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaço? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print ('É alfanumperico?', a.isalnum())
print ('Esta em maiúsculo?', a.isupper())
print ('Esta em minúsculas? ', a.islower())
print ('Esta capitalizada? ', a.istitle())