a = input('Enter something: ')
print('The primitive type of this value is ', type(a))
print('Is there only space? ', a.isspace())
print('Is it a number? ', a.isnumeric())
print('Is it alphabetical? ', a.isalpha())
print ('Is it alphanumeric?', a.isalnum())
print ('Is it capitalized?', a.isupper())
print ('Is it in lowercase? ', a.islower())
print ('Is this capitalized? ', a.istitle())