nome = input('Digite seu nome: ')
print('É um prazer conhecê-lo, {}!'.format(nome))
estado = input('Insira o estado: ')
print('Você mora no estado de, {}'.format(state))
cidade = input('Insira a cidade: ')
print('Você mora em, {}'.format(cidade))